# Generated by Django 3.2.8 on 2021-11-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botnethasher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='date_finished',
            field=models.DateTimeField(null=True, verbose_name='Finished datetime'),
        ),
    ]
